Update validate-pr.yml

diff --git a/.github/workflows/validate-pr.yml b/.github/workflows/validate-pr.yml
--- a/.github/workflows/validate-pr.yml
+++ b/.github/workflows/validate-pr.yml
@@ -10,5 +10,23 @@ jobs:
 
     steps:
       - name: Call PR Validation Endpoint
+        id: pr_validation
         run: |
-          curl -X GET "https://5351-217-111-217-82.ngrok-free.app/api/pr/analyze?prUrl=@${{ github.event.pull_request.html_url }}"
+          response=$(curl -X GET "https://5351-217-111-217-82.ngrok-free.app/api/pr/analyze?prUrl=@${{ github.event.pull_request.html_url }}")
+          echo "Response: $response"
+          valid=$(echo "$response" | jq '.pr.valid')
+          aiReview=$(echo "$response" | jq -r '.pr.aiReview')
+
+          # Mostrar la revisión con saltos de línea
+          echo "AI Review:"
+          echo "$aiReview" | sed 's/\\n/\n/g'
+
+          # Falla el check si "valid" es false
+          if [[ "$valid" == "false" ]]; then
+            echo "The PR validation failed. The check will fail."
+            exit 1
+          fi
+          
+      - name: Set status to success if validation passed
+        if: success()
+        run: echo "PR is valid, passing check."
